Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -71,6 +71,7 @@ jobs:
         run: |
           set -euo pipefail
           export PATH="$PATH:$HOME/.pesde/bin"
+          pesde install || { echo "Error: pesde install failed"; exit 1; }
           ls -a
           blink main || { echo "Error: Prebuild failed"; exit 1; }
 
@@ -78,6 +79,7 @@ jobs:
         run: |
           set -euo pipefail
           export PATH="$PATH:$HOME/.pesde/bin"
+          pesde install || { echo "Error: pesde install failed"; exit 1; }
           rojo build --output rcs.rbxlx || { echo "Error: Build failed"; exit 1; }
 
       - name: Create Release and Upload Artifact
